### ISSUE TITLE
Poetry installer script fails on Heroku-24 with an HTTP 404

### ISSUE THREAD

**Issue by edmorley** [moneymeets/python-poetry-buildpack#71]
Using this buildpack on Heroku-24 currently fails with:

```
-----> Python Poetry app detected
-----> No Poetry version specified in POETRY_VERSION config var. Defaulting to latest.
-----> Generate requirements.txt with Poetry
-----> Install Poetry
Traceback (most recent call last):
  File "<stdin>", line 314, in make
ModuleNotFoundError: No module named 'ensurepip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 945, in <module>
  File "<stdin>", line 923, in main
  File "<stdin>", line 560, in run
  File "<stdin>", line 581, in install
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "<stdin>", line 653, in make_env
  File "<stdin>", line 639, in make_env
  File "<stdin>", line 340, in make
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
       Retrieving Poetry metadata
       
       # Welcome to Poetry!
       
       This will download and install the latest version of Poetry,
       a dependency and package manager for Python.
       
       It will add the `poetry` command to Poetry's bin directory, located at:
       
       /app/.local/bin
       
       You can uninstall at any time by executing this script with the --uninstall option,
       and these changes will be reverted.
       
       Installing Poetry (1.8.3)
       Installing Poetry (1.8.3): Creating environment
 !     Push rejected, failed to compile Python Poetry app.
```

This is because:
1. Ubuntu 24.04's system Python is now Python 3.12 (as opposed to Ubuntu 20.04's Python 3.10)
2. The Poetry installer downloads the `virtualenv` package from URLs that contain the Python version like https://bootstrap.pypa.io/virtualenv/3.10/virtualenv.pyz
3. The upstream `virtualenv` project hasn't published the zipapp for Python 3.12 - ie: https://bootstrap.pypa.io/virtualenv/3.12/virtualenv.pyz doesn't exist yet

See:
https://github.com/python-poetry/install.python-poetry.org/issues/142
https://github.com/pypa/virtualenv/issues/2744

This will be resolved by:
https://github.com/pypa/get-virtualenv/pull/46

**Comment by mm-matthias** [comment]
@edmorley Thanks for your issue report.

What is the conclusion for this project? Do you want to wait until https://github.com/pypa/get-virtualenv/pull/46 gets resolved and then close this issue or is there something to do in this project?

**Comment by edmorley** [comment]
Hi! I opened this issue mainly for awareness, and so others didn't have to spend time debugging too.

The upstream virtualenv change has just been merged, so this buildpack should now work on Heroku-24 :-)

**Comment by mm-matthias** [comment]
@edmorley Very nice, thank you!
